baseURL = 'https://vincent-blog.top/'
languageCode = 'zh-cn'
title = '文森的科技博客'
theme = 'pehtheme-hugo'

summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = '专注于分享人工智能、个人创业经验、技术教程和潮品评测。探索AI应用、创业机遇和科技趋势的博客网站。'
	mainSections = 'posts'

[params.author]
	name = '文森Vincent'
	bio = '专注于AI应用、个人创业、技术教程和潮品分享的博主。分享实用知识和创新见解。'
	avatar = 'images/nasa-astronaut-unsplash.jpg'
	twitter = 'https://twitter.com/insertapps'

[pagination]
	pagerSize = 9 # <- Set the desired number of posts per page 

[menu] # Menu management
	[[menu.main]]
		name = '首页'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = '分类'
		pageRef = '/categories'
		weight = 15
	[[menu.main]]
		name = '标签'
		pageRef = '/tags'
		weight = 20
	[[menu.main]]
		name = '归档'
		pageRef = '/posts'
		weight = 25
	[[menu.main]]
		name = '关于'
		pageRef = '/about'
		weight = 30

[module]
	[module.hugoVersion]
		extended = false
		min = "0.116.0"
	[[module.mounts]] # Directing the static folder to assets.
	 	source = 'assets'
		target = 'static'

[params.comments]
  provider = 'giscus'
	repo = 'vincent-sha/sha-pehtheme-hugo'
	repoId = 'R_kgDOQUpLdQ'
	category = 'Announcements'
	categoryId = 'DIC_kwDOQUpLdc4Cx9E0'
	mapping = 'pathname'
	strict = '0'
	reactionsEnabled = '1'
	emitMetadata = '0'
	inputPosition = 'bottom'
	theme = 'preferred_color_scheme'
	lang = 'zh-CN'